For some reason, the zeroconf does not allow use the name 'test-device'. This files is used to test the API (without a device).
RuntimeError: Cannot initialize zeroconf service for 'test-device'The same name is already in use: you cannot run flowchem twice for the same device!