Important commit: Try to fix mypy error:
Reverse and build a better approach to the commit 173348b.

error: Argument "seconds" to "repeat_every" has incompatible type "RepeatedTaskInfo"; expected "float"  [arg-type]